# alternate debian bookworm dockerfile build (debian has pre-built python3-dbus-fast)
FROM debian:bookworm-slim
RUN mkdir -p home/cync2mqtt &&\
apt-get update && \
apt-get -y install python3 python3-pip python3-requests python3-yaml python3-six python3-dbus python3-passlib python3-docopt python3-pydbus git bluez python3-dbus-fast libglib2.0-dev && \
pip install --break-system-packages amqtt@git+https://github.com/Yakifo/amqtt.git git+https://github.com/juanboro/cync2mqtt.git 
COPY run.sh /
RUN chmod a+x /run.sh
CMD [ "/run.sh" ]
