#!/usr/bin/env python3
from acync import acync
import argparse
from pathlib import Path
import json
import yaml

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("configyaml",help="config yaml file to write")
    parser.add_argument("--jsonin",help="Optional input config JSON - default is to load from cloud")
    parser.add_argument("--jsonout",help="Optional output config JSON")
    args = parser.parse_args()

    if args.jsonin:
        with Path(args.jsonin).open("rt") as fp:
            meshinfo=json.load(fp)
    else:
        meshinfo=acync.get_app_meshinfo()

    with Path(args.configyaml).open("wt") as fp:
        yaml.dump(acync.app_meshinfo_to_configdict(meshinfo),fp)

    if args.jsonout:
        with Path(args.jsonout).open("wt") as fp:
            json.dump(meshinfo,fp)


if __name__ == "__main__":
    main()
